import { ThemeProvider } from "next-themes";
import "./globals.css";
import Header from "@/components/Header";



export const metadata = {
  title: "Herbst",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <body>
        <ThemeProvider enableSystem={true}>
          <Header />
            {children}
        </ThemeProvider>
        </body>
    </html>
  );
}
