import { ThemeProvider } from "next-themes";
import "./globals.css";
import Header from "@/components/Header";
import ScrollTracker from "@/components/ScrollTracker";
import { ReactNode } from "react";


export const metadata = {
  title: "Herbst",
  description: "Generated by create next app",
};

interface LayoutProps {
  children?: ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html suppressHydrationWarning>
      <body>
        <ThemeProvider enableSystem={true}>
          <ScrollTracker />
          <Header />
            {children}
        </ThemeProvider>
        </body>
    </html>
  );
}
