export const prefixes = {
    "countries": [
        { "code": "+93", "name": "Afghanistan", "shortName": "AFG" },
        { "code": "+355", "name": "Albania", "shortName": "ALB" },
        { "code": "+213", "name": "Algeria", "shortName": "ALG" },
        { "code": "+1 684", "name": "American Samoa", "shortName": "ASM" },
        { "code": "+376", "name": "Andorra", "shortName": "AND" },
        { "code": "+244", "name": "Angola", "shortName": "AGO" },
        { "code": "+1 264", "name": "Anguilla", "shortName": "AIA" },
        { "code": "+1 268", "name": "Antigua and Barbuda", "shortName": "ATG" },
        { "code": "+54", "name": "Argentina", "shortName": "ARG" },
        { "code": "+374", "name": "Armenia", "shortName": "ARM" },
        { "code": "+297", "name": "Aruba", "shortName": "ABW" },
        { "code": "+61", "name": "Australia", "shortName": "AUS" },
        { "code": "+672", "name": "Australian External Territories", "shortName": "AET" },
        { "code": "+43", "name": "Austria", "shortName": "AUT" },
        { "code": "+994", "name": "Azerbaijan", "shortName": "AZE" },
        { "code": "+1 242", "name": "Bahamas", "shortName": "BHS" },
        { "code": "+973", "name": "Bahrain", "shortName": "BHR" },
        { "code": "+880", "name": "Bangladesh", "shortName": "BGD" },
        { "code": "+1 246", "name": "Barbados", "shortName": "BRB" },
        { "code": "+1 268", "name": "Barbuda", "shortName": "ATG" },
        { "code": "+375", "name": "Belarus", "shortName": "BLR" },
        { "code": "+32", "name": "Belgium", "shortName": "BEL" },
        { "code": "+501", "name": "Belize", "shortName": "BLZ" },
        { "code": "+229", "name": "Benin", "shortName": "BEN" },
        { "code": "+1 441", "name": "Bermuda", "shortName": "BMU" },
        { "code": "+975", "name": "Bhutan", "shortName": "BTN" },
        { "code": "+591", "name": "Bolivia", "shortName": "BOL" },
        { "code": "+387", "name": "Bosnia and Herzegovina", "shortName": "BIH" },
        { "code": "+267", "name": "Botswana", "shortName": "BWA" },
        { "code": "+55", "name": "Brazil", "shortName": "BRA" },
        { "code": "+673", "name": "Brunei", "shortName": "BRN" },
        { "code": "+359", "name": "Bulgaria", "shortName": "BGR" },
        { "code": "+226", "name": "Burkina Faso", "shortName": "BFA" },
        { "code": "+257", "name": "Burundi", "shortName": "BDI" },
        { "code": "+855", "name": "Cambodia", "shortName": "CMD" },
        { "code": "+237", "name": "Cameroon", "shortName": "CMR" },
        { "code": "+1", "name": "Canada", "shortName": "CAN" },
        { "code": "+238", "name": "Cape Verde", "shortName": "CPV" },
        { "code": "+345", "name": "Cayman Islands", "shortName": "CYM" },
        { "code": "+236", "name": "Central African Republic", "shortName": "CAF" },
        { "code": "+235", "name": "Chad", "shortName": "TCD" },
        { "code": "+56", "name": "Chile", "shortName": "CHL" },
        { "code": "+86", "name": "China", "shortName": "CHN" },
        { "code": "+57", "name": "Colombia", "shortName": "COL" },
        { "code": "+269", "name": "Comoros", "shortName": "COM" },
        { "code": "+242", "name": "Congo", "shortName": "COG" },
        { "code": "+243", "name": "Congo, Dem. Rep. of (Zaire)", "shortName": "COD" },
        { "code": "+682", "name": "Cook Islands", "shortName": "COK" },
        { "code": "+506", "name": "Costa Rica", "shortName": "CRI" },
        { "code": "+385", "name": "Croatia", "shortName": "HRV" },
        { "code": "+53", "name": "Cuba", "shortName": "CUB" },
        { "code": "+599", "name": "Curacao", "shortName": "CUW" },
        { "code": "+357", "name": "Cyprus", "shortName": "CYP" },
        { "code": "+420", "name": "Czech Republic", "shortName": "CZE" },
        { "code": "+45", "name": "Denmark", "shortName": "DNK" },
        { "code": "+246", "name": "Diego Garcia", "shortName": "IOT" },
        { "code": "+253", "name": "Djibouti", "shortName": "DJI" },
        { "code": "+1 767", "name": "Dominica", "shortName": "DMA" },
        { "code": "+1 809", "name": "Dominican Republic", "shortName": "DOM" },
        { "code": "+670", "name": "East Timor", "shortName": "TLS" },
        { "code": "+56", "name": "Easter Island", "shortName": "CHL" },
        { "code": "+593", "name": "Ecuador", "shortName": "ECU" },
        { "code": "+20", "name": "Egypt", "shortName": "EGY" },
        { "code": "+503", "name": "El Salvador", "shortName": "SLV" },
        { "code": "+240", "name": "Equatorial Guinea", "shortName": "GNQ" },
        { "code": "+291", "name": "Eritrea", "shortName": "ERI" },
        { "code": "+372", "name": "Estonia", "shortName": "EST" },
        { "code": "+251", "name": "Ethiopia", "shortName": "ETH" },
        { "code": "+500", "name": "Falkland Islands", "shortName": "FLK" },
        { "code": "+298", "name": "Faroe Islands", "shortName": "FRO" },
        { "code": "+679", "name": "Fiji", "shortName": "FJI" },
        { "code": "+358", "name": "Finland", "shortName": "FIN" },
        { "code": "+33", "name": "France", "shortName": "FRA" },
        { "code": "+596", "name": "French Antilles", "shortName": "MTQ" },
        { "code": "+594", "name": "French Guiana", "shortName": "GUY" },
        { "code": "+689", "name": "French Polynesia", "shortName": "PYF" },
        { "code": "+241", "name": "Gabon", "shortName": "GAB" },
        { "code": "+220", "name": "Gambia", "shortName": "GMB" },
        { "code": "+995", "name": "Georgia", "shortName": "GEO" },
        { "code": "+49", "name": "Germany", "shortName": "GER" },
        { "code": "+233", "name": "Ghana", "shortName": "GHA" },
        { "code": "+350", "name": "Gibraltar", "shortName": "GIB" },
        { "code": "+30", "name": "Greece", "shortName": "GRC" },
        { "code": "+299", "name": "Greenland", "shortName": "GRL" },
        { "code": "+1 473", "name": "Grenada", "shortName": "GRD" },
        { "code": "+590", "name": "Guadeloupe", "shortName": "GLP" },
        { "code": "+1 671", "name": "Guam", "shortName": "GUM" },
        { "code": "+502", "name": "Guatemala", "shortName": "GTM" },
        { "code": "+224", "name": "Guinea", "shortName": "GIN" },
        { "code": "+245", "name": "Guinea-Bissau", "shortName": "GNB" },
        { "code": "+592", "name": "Guyana", "shortName": "GUY" },
        { "code": "+509", "name": "Haiti", "shortName": "HTI" },
        { "code": "+504", "name": "Honduras", "shortName": "HND" },
        { "code": "+852", "name": "Hong Kong", "shortName": "HKG" },
        { "code": "+36", "name": "Hungary", "shortName": "HUN" },
        { "code": "+354", "name": "Iceland", "shortName": "ISL" },
        { "code": "+91", "name": "India", "shortName": "IND" },
        { "code": "+62", "name": "Indonesia", "shortName": "IDN" },
        { "code": "+98", "name": "Iran", "shortName": "IRN" },
        { "code": "+964", "name": "Iraq", "shortName": "IRQ" },
        { "code": "+353", "name": "Ireland", "shortName": "IRL" },
        { "code": "+972", "name": "Israel", "shortName": "ISR" },
        { "code": "+39", "name": "Italy", "shortName": "ITA" },
        { "code": "+225", "name": "Ivory Coast", "shortName": "CIV" },
        { "code": "+1 876", "name": "Jamaica", "shortName": "JAM" },
        { "code": "+81", "name": "Japan", "shortName": "JPN" },
        { "code": "+962", "name": "Jordan", "shortName": "JOR" },
        { "code": "+7 7", "name": "Kazakhstan", "shortName": "KAZ" },
        { "code": "+254", "name": "Kenya", "shortName": "KEN" },
        { "code": "+686", "name": "Kiribati", "shortName": "KIR" },
        { "code": "+965", "name": "Kuwait", "shortName": "KWT" },
        { "code": "+996", "name": "Kyrgyzstan", "shortName": "KGZ" },
        { "code": "+855", "name": "Laos", "shortName": "LAO" },
        { "code": "+371", "name": "Latvia", "shortName": "LVA" },
        { "code": "+961", "name": "Lebanon", "shortName": "LBN" },
        { "code": "+266", "name": "Lesotho", "shortName": "LSO" },
        { "code": "+231", "name": "Liberia", "shortName": "LBR" },
        { "code": "+218", "name": "Libya", "shortName": "LBY" },
        { "code": "+423", "name": "Liechtenstein", "shortName": "LIE" },
        { "code": "+370", "name": "Lithuania", "shortName": "LTU" },
        { "code": "+352", "name": "Luxembourg", "shortName": "LUX" },
        { "code": "+261", "name": "Madagascar", "shortName": "MDG" },
        { "code": "+265", "name": "Malawi", "shortName": "MWI" },
        { "code": "+60", "name": "Malaysia", "shortName": "MYS" },
        { "code": "+960", "name": "Maldives", "shortName": "MDV" },
        { "code": "+223", "name": "Mali", "shortName": "MLI" },
        { "code": "+356", "name": "Malta", "shortName": "MLT" },
        { "code": "+692", "name": "Marshall Islands", "shortName": "MHL" },
        { "code": "+596", "name": "Martinique", "shortName": "MTQ" },
        { "code": "+222", "name": "Mauritania", "shortName": "MRT" },
        { "code": "+230", "name": "Mauritius", "shortName": "MUS" },
        { "code": "+52", "name": "Mexico", "shortName": "MEX" },
        { "code": "+691", "name": "Micronesia", "shortName": "FSM" },
        { "code": "+373", "name": "Moldova", "shortName": "MDA" },
        { "code": "+377", "name": "Monaco", "shortName": "MCO" },
        { "code": "+976", "name": "Mongolia", "shortName": "MNG" },
        { "code": "+382", "name": "Montenegro", "shortName": "MNE" },
        { "code": "+1 664", "name": "Montserrat", "shortName": "MSR" },
        { "code": "+212", "name": "Morocco", "shortName": "MAR" },
        { "code": "+258", "name": "Mozambique", "shortName": "MOZ" },
        { "code": "+95", "name": "Myanmar", "shortName": "MMR" },
        { "code": "+264", "name": "Namibia", "shortName": "NAM" },
        { "code": "+674", "name": "Nauru", "shortName": "NRU" },
        { "code": "+977", "name": "Nepal", "shortName": "NPL" },
        { "code": "+31", "name": "Netherlands", "shortName": "NLD" },
        { "code": "+687", "name": "New Caledonia", "shortName": "NCL" },
        { "code": "+64", "name": "New Zealand", "shortName": "NZL" },
        { "code": "+505", "name": "Nicaragua", "shortName": "NIC" },
        { "code": "+227", "name": "Niger", "shortName": "NER" },
        { "code": "+234", "name": "Nigeria", "shortName": "NGA" },
        { "code": "+683", "name": "Niue", "shortName": "NIU" },
        { "code": "+672", "name": "Norfolk Island", "shortName": "AUS" },
        { "code": "+1 670", "name": "Northern Mariana Islands", "shortName": "MNP" },
        { "code": "+47", "name": "Norway", "shortName": "NOR" },
        { "code": "+968", "name": "Oman", "shortName": "OMN" },
        { "code": "+92", "name": "Pakistan", "shortName": "PAK" },
        { "code": "+680", "name": "Palau", "shortName": "PLW" },
        { "code": "+970", "name": "Palestine", "shortName": "PSE" },
        { "code": "+507", "name": "Panama", "shortName": "PAN" },
        { "code": "+675", "name": "Papua New Guinea", "shortName": "PNG" },
        { "code": "+595", "name": "Paraguay", "shortName": "PRY" },
        { "code": "+51", "name": "Peru", "shortName": "PER" },
        { "code": "+63", "name": "Philippines", "shortName": "PHL" },
        { "code": "+48", "name": "Poland", "shortName": "POL" },
        { "code": "+351", "name": "Portugal", "shortName": "PRT" },
        { "code": "+1 787", "name": "Puerto Rico", "shortName": "PRI" },
        { "code": "+974", "name": "Qatar", "shortName": "QAT" },
        { "code": "+262", "name": "Reunion", "shortName": "REU" },
        { "code": "+40", "name": "Romania", "shortName": "ROU" },
        { "code": "+7", "name": "Russia", "shortName": "RUS" },
        { "code": "+250", "name": "Rwanda", "shortName": "RWA" },
        { "code": "+590", "name": "Saint Barthelemy", "shortName": "BLM" },
        { "code": "+290", "name": "Saint Helena", "shortName": "SHN" },
        { "code": "+1 869", "name": "Saint Kitts and Nevis", "shortName": "KNA" },
        { "code": "+1 758", "name": "Saint Lucia", "shortName": "LCA" },
        { "code": "+1 721", "name": "Saint Martin", "shortName": "SXM" },
        { "code": "+1 784", "name": "Saint Vincent and the Grenadines", "shortName": "VCT" },
        { "code": "+685", "name": "Samoa", "shortName": "WSM" },
        { "code": "+378", "name": "San Marino", "shortName": "SMR" },
        { "code": "+239", "name": "Sao Tome and Principe", "shortName": "STP" },
        { "code": "+966", "name": "Saudi Arabia", "shortName": "SAU" },
        { "code": "+221", "name": "Senegal", "shortName": "SEN" },
        { "code": "+381", "name": "Serbia", "shortName": "SRB" },
        { "code": "+248", "name": "Seychelles", "shortName": "SYC" },
        { "code": "+232", "name": "Sierra Leone", "shortName": "SLE" },
        { "code": "+65", "name": "Singapore", "shortName": "SGP" },
        { "code": "+421", "name": "Slovakia", "shortName": "SVK" },
        { "code": "+386", "name": "Slovenia", "shortName": "SVN" },
        { "code": "+677", "name": "Solomon Islands", "shortName": "SLB" },
        { "code": "+252", "name": "Somalia", "shortName": "SOM" },
        { "code": "+27", "name": "South Africa", "shortName": "ZAF" },
        { "code": "+82", "name": "South Korea", "shortName": "KOR" },
        { "code": "+211", "name": "South Sudan", "shortName": "SSD" },
        { "code": "+34", "name": "Spain", "shortName": "ESP" },
        { "code": "+94", "name": "Sri Lanka", "shortName": "LKA" },
        { "code": "+249", "name": "Sudan", "shortName": "SDN" },
        { "code": "+597", "name": "Suriname", "shortName": "SUR" },
        { "code": "+268", "name": "Swaziland", "shortName": "SWZ" },
        { "code": "+46", "name": "Sweden", "shortName": "SWE" },
        { "code": "+41", "name": "Switzerland", "shortName": "SWT" },
        { "code": "+963", "name": "Syria", "shortName": "SYR" },
        { "code": "+886", "name": "Taiwan", "shortName": "TWN" },
        { "code": "+992", "name": "Tajikistan", "shortName": "TJK" },
        { "code": "+255", "name": "Tanzania", "shortName": "TZA" },
        { "code": "+66", "name": "Thailand", "shortName": "THA" },
        { "code": "+670", "name": "Timor-Leste", "shortName": "TLS" },
        { "code": "+228", "name": "Togo", "shortName": "TGO" },
        { "code": "+690", "name": "Tokelau", "shortName": "TKL" },
        { "code": "+676", "name": "Tonga", "shortName": "TON" },
        { "code": "+1 868", "name": "Trinidad and Tobago", "shortName": "TTO" },
        { "code": "+216", "name": "Tunisia", "shortName": "TUN" },
        { "code": "+90", "name": "Turkey", "shortName": "TUR" },
        { "code": "+993", "name": "Turkmenistan", "shortName": "TKM" },
        { "code": "+1 649", "name": "Turks and Caicos Islands", "shortName": "TCA" },
        { "code": "+688", "name": "Tuvalu", "shortName": "TUV" },
        { "code": "+256", "name": "Uganda", "shortName": "UGA" },
        { "code": "+380", "name": "Ukraine", "shortName": "UKR" },
        { "code": "+971", "name": "United Arab Emirates", "shortName": "UAE" },
        { "code": "+44", "name": "United Kingdom", "shortName": "GBR" },
        { "code": "+1", "name": "United States", "shortName": "USA" },
        { "code": "+598", "name": "Uruguay", "shortName": "URY" },
        { "code": "+998", "name": "Uzbekistan", "shortName": "UZB" },
        { "code": "+678", "name": "Vanuatu", "shortName": "VUT" },
        { "code": "+379", "name": "Vatican City", "shortName": "VAT" },
        { "code": "+58", "name": "Venezuela", "shortName": "VEN" },
        { "code": "+84", "name": "Vietnam", "shortName": "VNM" },
        { "code": "+681", "name": "Wallis and Futuna", "shortName": "WLF" },
        { "code": "+967", "name": "Yemen", "shortName": "YEM" },
        { "code": "+260", "name": "Zambia", "shortName": "ZMB" },
        { "code": "+263", "name": "Zimbabwe", "shortName": "ZWE" }
    ]
};
